---
  - name: Instalando apache
    apt: name=apache2 state=present
  - name: Nuevo sitio virtual
    template:
       src=sitioansible.conf.j2
       dest=/etc/apache2/sites-available/sitioiaw.conf
  - name: borrar virtual host por defecto
    file:
      path=/etc/apache2/sites-enabled/000-default.conf
      state=absent
  - name: borrar index por defecto
    file:
      path=/var/www/html/index.html
      state=absent
  - name: Nuevo index
    template:
       src=index.html
       dest=/var/www/html/index.html
  - name: Añadir info.php
    template:
       src=info.php
       dest=/var/www/html/info.php
  - name: Activar el nuevo sitio
    file:
       src=/etc/apache2/sites-available/sitioiaw.conf
       dest=/etc/apache2/sites-enabled/sitioiaw.conf
       state=link
  - name: Activar modulo de apache
    apache2_module: state=present name=userdir
    notify:
      - reiniciando apache
